# Generated by Django 3.0.3 on 2020-02-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.IntegerField(verbose_name=1)),
                ('sec', models.CharField(max_length=1)),
                ('grad_year', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fcs',
            fields=[
                ('fcs_id', models.AutoField(primary_key=True, serialize=False)),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Class')),
            ],
        ),
        migrations.CreateModel(
            name='fcss',
            fields=[
                ('fcss_id', models.AutoField(primary_key=True, serialize=False)),
                ('fcs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.fcs')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_code', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_no', models.CharField(max_length=5)),
                ('qp_pattern', models.FileField(upload_to='')),
                ('fcs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.fcs')),
            ],
        ),
        migrations.CreateModel(
            name='Test_res',
            fields=[
                ('testres_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.FileField(upload_to='')),
                ('fcs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.fcs')),
                ('fcss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.fcss')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=5)),
                ('blood_group', models.CharField(max_length=2)),
                ('father_name', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('parent_mail', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('C10th_res', models.FloatField()),
                ('C12th_res', models.FloatField()),
                ('student_pic', models.ImageField(upload_to='')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Class')),
            ],
        ),
        migrations.AddField(
            model_name='fcss',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Student'),
        ),
        migrations.AddField(
            model_name='fcs',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='classteacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('hour', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.SmallIntegerField()),
                ('fcss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.fcss')),
            ],
        ),
    ]
