# Generated by Django 3.0.3 on 2020-02-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eigth')])),
                ('sec', models.CharField(max_length=1)),
                ('graduation_year', models.PositiveSmallIntegerField(null=True)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SI', 'Single'), ('MA', 'Married'), ('DI', 'Divorced'), ('WI', 'Widowed'), ('SE', 'Seperated')], max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('teacher_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('association_with_institution', models.CharField(blank=True, choices=[('R', 'Regular'), ('V', 'Visiting'), ('A', 'Adjunct'), ('C', 'Contract')], max_length=20, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fcs',
            fields=[
                ('fcs_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Class')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Fcss',
            fields=[
                ('fcss_id', models.AutoField(primary_key=True, serialize=False)),
                ('fcs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Fcs')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_code', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_description', models.CharField(choices=[('P', 'Principal'), ('H', 'Head of Department'), ('C', 'Class Teacher'), ('S', 'Subject Teacher'), ('M', 'Mentor')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('workshop_id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop_detail', models.TextField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('work_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_no', models.CharField(max_length=5)),
                ('qp_pattern', models.FileField(upload_to='')),
                ('fcs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Fcs')),
            ],
        ),
        migrations.CreateModel(
            name='Test_res',
            fields=[
                ('testres_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.FileField(upload_to='')),
                ('fcss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Fcss')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=5)),
                ('blood_group', models.CharField(max_length=2)),
                ('father_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('parent_mail', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('c10th_res', models.FloatField()),
                ('c12th_res', models.FloatField()),
                ('student_pic', models.ImageField(upload_to='')),
                ('deleted', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Class')),
            ],
        ),
        migrations.CreateModel(
            name='SessionChair',
            fields=[
                ('session_chair_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_chair_details', models.TextField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('research_paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('research_paper_details', models.TextField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_detail', models.TextField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='LoginAuthKey',
            fields=[
                ('login_authkey_id', models.AutoField(primary_key=True, serialize=False)),
                ('authkey', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='fcss',
            name='student_id',
            field=models.ManyToManyField(to='api1.Student'),
        ),
        migrations.AddField(
            model_name='fcs',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Subject'),
        ),
        migrations.CreateModel(
            name='FacultyQualification',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('percentage', models.FloatField(max_length=4)),
                ('graduation_year', models.PositiveSmallIntegerField(null=True)),
                ('university', models.CharField(max_length=100)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.ManyToManyField(to='api1.Type'),
        ),
        migrations.AddField(
            model_name='class',
            name='classteacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('hour', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('fcss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Fcss')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfSpecialisation',
            fields=[
                ('specialiation_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialiation_details', models.TextField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRole',
            fields=[
                ('academic_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_role_details', models.TextField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Faculty')),
            ],
        ),
    ]
