# Generated by Django 3.0.3 on 2020-02-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrole',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='areaofspecialisation',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='facultyqualification',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='sessionchair',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='workshops',
            name='faculty_id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='academic_roles',
            field=models.ManyToManyField(to='api1.AcademicRole'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='area_of_specialisation',
            field=models.ManyToManyField(to='api1.AreaOfSpecialisation'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_qualifications',
            field=models.ManyToManyField(to='api1.FacultyQualification'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='publications',
            field=models.ManyToManyField(to='api1.Publications'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_papers',
            field=models.ManyToManyField(to='api1.ResearchPaper'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='session_chairs',
            field=models.ManyToManyField(to='api1.SessionChair'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='work_experiences',
            field=models.ManyToManyField(to='api1.WorkExperience'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='workshops',
            field=models.ManyToManyField(to='api1.Workshops'),
        ),
    ]
