# Generated by Django 3.0.3 on 2020-02-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_auto_20200228_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='academic_roles',
            field=models.ManyToManyField(blank=True, null=True, to='api1.AcademicRole'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='area_of_specialisation',
            field=models.ManyToManyField(blank=True, null=True, to='api1.AreaOfSpecialisation'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_qualifications',
            field=models.ManyToManyField(blank=True, null=True, to='api1.FacultyQualification'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='publications',
            field=models.ManyToManyField(blank=True, null=True, to='api1.Publications'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_papers',
            field=models.ManyToManyField(blank=True, null=True, to='api1.ResearchPaper'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='session_chairs',
            field=models.ManyToManyField(blank=True, null=True, to='api1.SessionChair'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, null=True, to='api1.WorkExperience'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='workshops',
            field=models.ManyToManyField(blank=True, null=True, to='api1.Workshops'),
        ),
    ]
